name: List 3 actions
on: [push]
jobs:
  Check-versions:
    runs-on: ubuntu-latest
    steps:
      - run: python -V
      - run: docker --version
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Installing libs
        run: pip install -r requirements.txt
      - name: Testing app.py
        run: pylint app.py
  Building-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up buildx
        uses: docker/setup-buildx-action@v1
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: test-flask-app
